name: Static analysis

on: push

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0, 8.1, 8.2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Cache Composer Dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ./src/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        uses: php-actions/composer@v6
        with:
          working_dir: './src'
          php_version: ${{ matrix.php }}

      - name: "Running PHPStan..."
        working-directory: './src'
        run: vendor/bin/phpstan --no-progress
